CREATE TABLE tag (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE category (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  image_link TEXT,
  updatedAt TIMESTAMP,
  createdAt TIMESTAMP NOT NULL DEFAULT now()
);


CREATE TABLE product (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  sku VARCHAR(255) NOT NULL,
  unit_price DECIMAL NOT NULL,
  currency VARCHAR(10) NOT NULL,
  image_link TEXT NOT NULL,
  color VARCHAR(255),
  size VARCHAR(255),
  updatedAt TIMESTAMP,
  createdAt TIMESTAMP NOT NULL DEFAULT now(),
  categoryId INTEGER NOT NULL,
  
  FOREIGN KEY (categoryId) REFERENCES Category(id)
  
);


CREATE TABLE inventory (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  quantity INT NOT NULL,
  productId INTEGER NOT NULL,
  
  FOREIGN KEY (productId) REFERENCES Product(id)
);



CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  phoneNumber VARCHAR(255) NOT NULL,
  username VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);